name: Package and Release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Package and Release
        uses: BigWigsMods/packager@master